// <auto-generated />
namespace Kino.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removedICollections1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedICollections1));
        
        string IMigrationMetadata.Id
        {
            get { return "201808172122357_removedICollections1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
